name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: asia-southeast2
  CICD_CREDENTIALS: ${{ secrets.CICD_CREDENTIALS }}
  GCP_ARTIFACT_NAME: ${{ secrets.GCP_ARTIFACT_NAME }}
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.CICD_CREDENTIALS }}'
          
      # Setup gcloud CLI
      - uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        
      - name: Set Environment Variables
        run: |
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
            echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
            echo "DB_PASS=${{ secrets.DB_PASS }}" >> $GITHUB_ENV
            echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
            echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> $GITHUB_ENV
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
            echo "CLOUD_STORAGE_CREDENTIALS=${{ secrets.CLOUD_STORAGE_CREDENTIALS }}" >> $GITHUB_ENV
            echo "TTS_CREDENTIALS=${{ secrets.TTS_CREDENTIALS }}" >> $GITHUB_ENV
            echo "CICD_CREDENTIALS=${{ secrets.CICD_CREDENTIALS }}" >> $GITHUB_ENV
            echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> $GITHUB_ENV
            echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
            echo "GCP_ARTIFACT_NAME=${{ secrets.GCP_ARTIFACT_NAME }}" >> $GITHUB_ENV

      # Build and push image to Google Container Registry
      - name: Build
        run: |
         - gcloud builds submit \
            --tag asia-southeast2-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_NAME/sibi-backend-image:$GITHUB_SHA . \
            --substitutions=DB_HOST=${DB_HOST}, \
            DB_PORT=${{ secrets.DB_PORT }}, \
            DB_USER=${{ secrets.DB_USER }}, \
            DB_PASS=${{ secrets.DB_PASS }}, \
            PORT=${{ secrets.PORT }}, \
            DB_DIALECT=${{ secrets.DB_DIALECT }}, \
            DB_NAME=${{ secrets.DB_NAME }}, \
            CLOUD_STORAGE_CREDENTIALS=${{ secrets.CLOUD_STORAGE_CREDENTIALS }}, \
            TTS_CREDENTIALS=${{ secrets.TTS_CREDENTIALS }}, \
            CICD_CREDENTIALS=${{ secrets.CICD_CREDENTIALS }}, \
            BUCKET_NAME=${{ secrets.BUCKET_NAME }}, \
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}, \
            GCP_ARTIFACT_NAME=${{ secrets.GCP_ARTIFACT_NAME }}
        
      - name: Deploy
        run: gcloud run deploy sibi-dev --image asia-southeast2-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_NAME/sibi-backend-image:$GITHUB_SHA --platform managed --region $RUN_REGION --port 8080
