name: Deploy to Cloud Run
on:
  push:
    branches: [main, chore/*]

env:
  GCP_PROJECT_ID: capstone-sibi
  RUN_REGION: asia-southeast2
  CICD_CREDENTIALS: ${{ secrets.CICD_CREDENTIALS }}
  GCP_ARTIFACT_NAME: artifact-sibi
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.CICD_CREDENTIALS }}'
          
      # Setup gcloud CLI
      - uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        
      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag asia-southeast2-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_NAME/sibi-backend-image:$GITHUB_SHA .
        
      - name: Deploy
        run: gcloud run deploy sibi-dev --image asia-southeast2-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_NAME/sibi-backend-image:$GITHUB_SHA --platform managed --region $RUN_REGION